var keys = {
    '1': 'Java Basic Concepts',
    '2': 'Balanced Bracket Algorithm',
    '3': 'Comparable vs Comparator (Java)',
    '4': 'Set vs List vs Map (Java)',
    '5': 'Static vs Instance variables (Java)',
    '6': 'Memory profiling (JVM)',
    '7': 'Declaration and Access Control (Java)',
    '8': 'Lambda Functions (Java 8)',
    '9': 'Functional Interfaces (Java 8)',
    '10': 'Completable Future - Java 8',
    '11': 'Java 8 Streams',
    '12': 'Hibernate cascade all-delete-orphan',
    '13': 'Hibernate Enum String vs Ordinal',
    '14': 'EC2 - Elastic Cloud Compute Basics',
    '15': 'Autoscaling AWS',
    '16': 'EBS vs EFS – Amazon WebServices',
    '17': 'Amazon RDS - Relational Database Service',
    '18': 'S3 - Simple Storage Service',
    '19': 'How does Amazon Storage Gateway work',
    '20': 'How does Amazon Storage Gateway work',
    '21': 'IAM (Identity and Access Management) - AWS',
    '22': 'VPC Peering - AWS',
    '23': 'VPC Virtual Private Cloud - AWS',
    '24': 'Route 53 – AWS DNS Server',
    '25': 'SQS - Simple Queue Service - AWS',
    '26': 'SNS – Simple Notification Service - AWS',
    '27': 'Kinesis AWS',
    '28': 'Cloudwatch - AWS',
    '29': 'Exam Notes 1 - Solutions Architect Associate AWS',
    '30': 'Exam Notes 2 - Solutions Architect Associate AWS',
    '31': 'Exam Notes 3 - Solutions Architect Associate AWS',
    '32': 'Exam Notes - Soft Limits - Solutions Architect Associate AWS',
    '33': 'Well Architected Framework',
    '34': 'What is Docker',
    '35': 'What is Docker',
    '36': 'Advanced Docker (docker swarm, network, secrets, etc)',
    '37': 'Akka Ask',
    '38': 'Akka Immutable Messages',
    '39': 'Akka Actor Model',
    '40': 'Akka Actor Heirarchy',
    '41': 'React',
    '42': 'Redux',
    '43': 'Cassandra',
    '44': 'Prime Numbers and Summation',
    '45': 'Running a React app on Docker',
    '46': 'What is Big O Notation',
    '47': 'Euler 1 - Sum of all numbers to N',
    '48': 'ES6 Basics Part 1',
    '49': 'Euler 2 - Even Fibonacci',
    '50': 'How to setup LightSail with GoDaddy, route 53 or any DNS',
    '51': 'Throttling + Java Atomic Library',
    '52': 'Basic Kubernetes, Running Local Minikube',
    '53': 'Short Introduction to Grails',
    '54': 'Apache Kafka Basics - Topics, Partitions and Brokers',
    '55': 'How to install Docker on EC2',
    '56': 'NGORK - Making An API call from Staging environment to your Local Host',
    '57': 'Creating Local CI/CD Using Jenkins Server (Docker + AWS)',
    '58': 'Multiple Kafka Brokers with replication',
    '59': 'Big O Notation for Dummies',
    '60': 'Data Structure - Stack',
    '61': 'Data Structure - Queue',
    '62': 'Introduction to Python',
    '63': 'Python Basics - Lists'

};

exports.keys = keys;